version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpw
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8082:8081"
    volumes:
      - nexus-data:/nexus-data
  common:
    build:
      context: ./common
      dockerfile: Dockerfile
    container_name: common-builder
    depends_on:
      - nexus
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_LOG_CLEANUP_POLICY: "compact"
  kafka-init:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-init
    depends_on:
      - kafka
    command: |
      bash -c "
        until kafka-topics --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
          echo 'Waiting for Kafka...'; sleep 2;
        done;

        kafka-topics --create \
          --if-not-exists \
          --topic project-events \
          --bootstrap-server kafka:9092 \
          --partitions 6 \
          --replication-factor 1 \
          --config cleanup.policy=compact \
          --config retention.ms=-1 \
          --config min.cleanable.dirty.ratio=0.01 || echo 'Topic exists or failed';

        echo 'Kafka topic setup complete.';
      "
  redis:
    image: "redis:latest"
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379"
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8087:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
  thirdparty:
    build:
      context: ./thirdparty
      dockerfile: Dockerfile
    container_name: thirdparty
    depends_on:
      - postgres
      - nexus
      - kafka
      - common
    ports:
      - "8083:8080"
  deltabridge:
    build:
      context: ./deltabridge
      dockerfile: Dockerfile
    container_name: deltabridge
    depends_on:
      - common
      - kafka
      - redis
    ports:
      - "8086:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  vue-app:
    build:
      context: ./vuetify
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8089:80"
    restart: unless-stopped
    depends_on:
      - deltabridge
    environment:
      - VUE_APP_WS_URL=ws://localhost:8086/ws
volumes:
  nexus-data:
  postgres_data:
  redis-data:
